### ISSUE TITLE
Aria for Loading Spinnner

### ISSUE THREAD

**Issue by kendallgassner** [intuit/accessibility-snippets#32]
This one is a little more open ended but I think loading spinners are usually forgotten about. 

this snippet might include `aria-live="polite"` and `role="status"` aria-label='loading'

essentially we want developers to be able to create a div with aria-live and role=status to explain to a screen-reader user that the page is loading 

https://codeburst.io/how-to-create-a-simple-css-loading-spinner-make-it-accessible-e5c83c2e464c

**Comment by aylinmarie** [comment]
I don't mind taking this on! :)
