### ISSUE TITLE
css snippet @media (prefers-color-scheme: light) {}

### ISSUE THREAD

**Issue by kendallgassner** [intuit/accessibility-snippets#39]
The prefers-color-scheme CSS media feature is used to detect if the user has requested a light or dark color theme.

The user might indicate this preference through an operating system setting (e.g. light or dark mode) or a user agent setting.

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

```
@media (prefers-color-scheme: light) {}
```

**Comment by aylinmarie** [comment]
Happy to take this on!
