### ISSUE TITLE
Re-organize react-snippets keys to be alphabetical

### ISSUE THREAD

**Issue by jeffreyclu** [intuit/accessibility-snippets#53]
**Is your feature request related to a problem? Please describe.**

Currently the code snippets in `react-snippets` aren't sorted alphabetically by key.

**Describe the solution you'd like**

Re-organize the keys so that they are alphabetical based on https://eslint.org/docs/rules/sort-keys. Then the test that accounts for this sorting can be re-incorporated.

**Describe alternatives you've considered**

**Additional context**

Related PR: https://github.com/intuit/accessibility-snippets/pull/44

**Comment by syedareehaquasar** [comment]
I would Like to work on this issue!
